---
title: "Bamboo"
subtitle: "GFD Project (Draft Version)"
author: "Nguyen Chi Dung"

output:
  tufte::tufte_html: default
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
bibliography: skeleton.bib
link-citations: yes
---

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'), warning = FALSE, message = FALSE)
options(htmltools.dir.version = FALSE)
```

```{r}
#======================================
# create a connection with PostgreSQL
#======================================

# loads the PostgreSQL driver: 
rm(list = ls())
library("RPostgreSQL")
drv <- dbDriver("PostgreSQL")

# creates a connection to the postgres database. Note that "con" 
# will be used later in each connection to the database: 

con <- dbConnect(drv, 
                 dbname = "db_bamboo",
                 host = "test.gfd.com.vn", 
                 port = 5432,
                 user = "dungtiensinh", 
                 password = "12@45")


# check for the cartable: 
dbExistsTable(con, "tbl_points")

#=============================
# Import data from data base
#=============================

df_postgres <- dbGetQuery(con, "SELECT * from tbl_points")

# close the connection: 
dbDisconnect(con)

# Inspect our data: 
library(tidyverse)
df_postgres %>% head()
df_postgres %>% dim()
df_postgres %>% names()
df_postgres$country %>% table()
```

